version: '3'

services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    container_name: postgres
    volumes:
      - ./local-initdb.sql:/docker-entrypoint-initdb.d/local-initdb.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
