server:
  port: ${PORT:8080}
  address: 0.0.0.0

feign:
  url:
    currency-api-key: ${CURRENCY_CLIENT_API_KEY:}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: ${DB_USER:liquibase_user}
    password: ${DB_PASSWORD:liquibase_password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:currency_rate_db}
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:currency_rate_db}
  liquibase:
    change-log: classpath:migrations/master.xml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  application:
    name: currency-rate
logging:
  level:
    root: info
